// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTYzPCnU46V2BpxdjdMLtizZ4AYxAhHws',
    appId: '1:914049158539:web:e2f568a0e6aebcc836338e',
    messagingSenderId: '914049158539',
    projectId: 'aatt-b3e3e',
    authDomain: 'aatt-b3e3e.firebaseapp.com',
    storageBucket: 'aatt-b3e3e.firebasestorage.app',
    measurementId: 'G-W6BBDYV7XZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABw7d0VVL7CtJeelwbbRn6GnfvoLcK5Ls',
    appId: '1:914049158539:android:dbb93b0e1bd154d636338e',
    messagingSenderId: '914049158539',
    projectId: 'aatt-b3e3e',
    storageBucket: 'aatt-b3e3e.firebasestorage.app',
  );

static const FirebaseOptions ios = FirebaseOptions(
  apiKey: 'AIzaSyCAobV1nrUyqUGQsQJxlbVgKFWp34jdVSk',
  appId: '1:914049158539:ios:0215f7eca17c5f0836338e',
  messagingSenderId: '914049158539',
  projectId: 'aatt-b3e3e',
  storageBucket: 'aatt-b3e3e.firebasestorage.app',
  iosBundleId: 'com.palatenetworks.aatt',
);

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCuXZr2S-5pGGgqhbQP9vkDVmbN1PAK3o',
    appId: '1:914049158539:ios:bf82c5b92c2fa85936338e',
    messagingSenderId: '914049158539',
    projectId: 'aatt-b3e3e',
    storageBucket: 'aatt-b3e3e.firebasestorage.app',
    iosBundleId: 'com.palatenetworks.aatt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTYzPCnU46V2BpxdjdMLtizZ4AYxAhHws',
    appId: '1:914049158539:web:e2f568a0e6aebcc836338e',
    messagingSenderId: '914049158539',
    projectId: 'aatt-b3e3e',
    authDomain: 'aatt-b3e3e.firebaseapp.com',
    storageBucket: 'aatt-b3e3e.firebasestorage.app',
    measurementId: 'G-W6BBDYV7XZ',
  );

}